# Generated by Django 2.2.20 on 2021-05-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tscode', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('listdate', models.CharField(max_length=200)),
                ('commonuser', models.ManyToManyField(to='User.CommonUser')),
            ],
        ),
    ]
