# Generated by Django 3.2 on 2021-05-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='predictdate',
            field=models.CharField(default='abc', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='predictprice',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
