# Generated by Django 3.2 on 2021-05-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='desc',
            new_name='description',
        ),
    ]
